### PR TITLE
Bug Fix for proper position of tooltip

### PR DESCRIPTION
**Pull request by ghost**
/cc @arunkumars08

### CODE REVIEW

**Comment by arunkumars08** [comment]
It seems to have conflicts. Please resolve and raise request again

**Comment by arunkumars08** [comment]
@sudharsanam

**Comment by ghost** [comment]
@arunkumars08 : Could you please review ? Merge conflicts are resolved!

**Review by arunkumars08 — COMMENTED** [review]
LGTM 👍

**Pull request merged**
