### PR TITLE
Readme file for the REPO

### PR DESCRIPTION
**Pull request by ghost**
Read me file for the repository

 Contents: 
   1. Repo details
   2. References for the repo
   3. Usage Details 

Usage details are yet to be updated.

/cc @arunkumars08

### CODE REVIEW

**Comment by arunkumars08** [comment]
@sudharsanam: This basic writeup looks good. Going forward we 'll have guidelines on structuring the readme. Moreover we should provide a link as guidelines for contribution for those who wish to do.

**Comment by arunkumars08** [comment]
@sudharsanam : 👍

**Comment by arunkumars08** [comment]
We 'll have a guideline that once we see LGTM (Looks Good To Me) and 👍 it means it is ok to push.
LGTM 👍

**Comment by ghost** [comment]
👍

**Pull request merged**
