### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by arunkumars08**
Edited Readme.md to look more meaningful and clearer.

### CODE REVIEW

**Comment by arunkumars08** [comment]
@sudharsanam

**Comment by arunkumars08** [comment]
@mageshwaranr

**Comment by ghost** [comment]
@arunkumars08 : I have modified the organization name to jstweak. Could you please update your document accordingly?

**Comment by ghost** [comment]
otherwise, the readme looks fine. We will update more examples after we complete our task.

**Comment by arunkumars08** [comment]
Alternatively, I was thinking of these names - TypeJava(script), PlanJS, JsHurdle, OneStopJS, ProjectJS

**Comment by ghost** [comment]
@arunkumars08 : Lets go with jsHurdle 👍

**Pull request merged**
